name: Run Branch Protection

on:
  workflow_dispatch:
    inputs:
      parameter:
        description: "Reason for Locking"
        required: false
        type:  string

jobs:
  job-id:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: venh/branch-protection@v1.0.0
       with:
        token: '${{ secrets.GH_TOKEN_TESTREPO }}' 
        org: 'Addepar' 
        rulesPath: .github/config/rules.json 
        includedReposPath: .github/config/includedRepos.txt
        action: set
